services:
  - type: web
    name: arihna-biha
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        value: "sqlite+aiosqlite:///./arihna_biha.db"
